# Generated by Django 2.0 on 2018-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.CharField(max_length=75)),
                ('password1', models.CharField(max_length=30)),
                ('accountname', models.CharField(max_length=40)),
                ('primaryaddress', models.CharField(blank=True, max_length=100)),
                ('contactnumber', models.CharField(blank=True, max_length=35)),
            ],
            options={
                'db_table': 'Profile Data',
                'ordering': ('accountname', 'mailid'),
            },
        ),
    ]
