# Generated by Django 2.0 on 2018-01-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile_Data',
        ),
    ]
