# Generated by Django 2.0 on 2018-01-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField(unique=True)),
                ('status', models.BooleanField()),
                ('posterName', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=35)),
                ('mailid', models.CharField(max_length=50, null=True)),
                ('defintion', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dummy_posts',
                'ordering': ('-date', '-time', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('imagefile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('accountName', models.CharField(max_length=30)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('primaryLocation', models.CharField(max_length=100)),
                ('secondaryLocation', models.CharField(max_length=100, null=True)),
                ('mobileNumbers', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='postedin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
