# Generated by Django 2.0 on 2018-01-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180120_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummypost',
            name='postid',
        ),
    ]
