# Generated by Django 2.0 on 2018-01-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180121_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
